force-app/main/default/objects/MassRecordUpdater_Objects__mdt/MassRecordUpdater_Objects__mdt.object-meta.xml
<CustomObject>
    <description>API Names of objects whose fields we want to update</description>
    <label>MassRecordUpdater Object</label>
    <pluralLabel>MassRecordUpdater Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/MassRecordUpdater_Process__mdt/MassRecordUpdater_Process__mdt.object-meta.xml
<CustomObject>
    <description>Create an update process for each object</description>
    <label>MassRecordUpdater Process</label>
    <pluralLabel>MassRecordUpdater Processes</pluralLabel>
</CustomObject>

force-app/main/default/objects/MassRecordUpdater_Process__mdt/fields/Current_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Current_Field_Value__c</fullName>
    <label>Current Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassRecordUpdater_Process__mdt/fields/MassRecordUpdater_Object__c.field-meta.xml
<CustomField>
    <fullName>MassRecordUpdater_Object__c</fullName>
    <label>MassRecordUpdater Object</label>
    <referenceTo>MassRecordUpdater_Objects__mdt</referenceTo>
    <relationshipLabel>MassRecordUpdater Processes</relationshipLabel>
    <relationshipName>MassRecordUpdater_Processes</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/MassRecordUpdater_Process__mdt/fields/New_Field_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Field_Value__c</fullName>
    <label>New Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MassRecordUpdater_Process__mdt/fields/Require_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Require_Criteria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Criteria</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/custommetadata.cls
public class custommetadata {
    static sObject anObject;
        public static void updateObject () {
            Map<Id,MassRecordUpdater_Objects__mdt> apiNames = 
                new Map<Id,MassRecordUpdater_Objects__mdt>([SELECT Id, Object_API_Name__c FROM MassRecordUpdater_Objects__mdt]);
            MassRecordUpdater_Process__mdt processDefinition = 
                [SELECT Require_Criteria__c, New_Field_Value__c, MassRecordUpdater_Object__c,Field_API_Name__c, Current_Field_Value__c FROM MassRecordUpdater_Process__mdt];
            
            system.debug('apiNames: ' + apiNames);
            system.debug('processDefinition: ' + processDefinition);
            system.debug('apiName is: ' + apiNames.get(processDefinition.MassRecordUpdater_Object__c).Object_API_Name__c);
            
            String query = 'SELECT ' + processDefinition.Field_API_Name__c + ' FROM ' + apiNames.get(processDefinition.MassRecordUpdater_Object__c).Object_API_Name__c;
            
            system.debug('query: ' + query);
            
            sObject anObject = database.query(query);
            system.debug('anObject: ' + anObject);
            system.debug('anObject field: ' + anObject.get(processDefinition.Field_API_Name__c));
            anObject.put(processDefinition.Field_API_Name__c, processDefinition.New_Field_Value__c);
            
            update anObject;
            
            
        }
 }